# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0.xci
# IP: The module: 'EQ_27_band_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ_27_band_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ_27_band_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ_27_band_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0.xci
# IP: The module: 'EQ_27_band_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ_27_band_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ_27_band_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ_27_band_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
