set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/LRCLK]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list EQ_27_band_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[0]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[1]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[2]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[3]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[4]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[5]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[6]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[7]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[8]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[9]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[10]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[11]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[12]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[13]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[14]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[15]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[16]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[17]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[18]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[19]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[20]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[21]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[22]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[23]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[24]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[25]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[26]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[27]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[28]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[29]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[30]} {EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list EQ_27_band_i/LRCLK]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
