set_property MARK_DEBUG true [get_nets SDATA_I_IBUF]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0/inst/bclk]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0/inst/lrclk]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tready]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tlast]
set_property MARK_DEBUG true [get_nets EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_aresetn]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[16]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[17]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[18]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[19]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[20]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[21]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[22]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[23]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[24]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[25]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[26]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[27]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[28]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[29]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[30]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[31]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[9]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list EQ_27_band_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[0]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[1]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[2]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[3]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[4]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[5]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[6]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[7]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[8]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[9]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[10]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[11]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[12]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[13]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[14]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[15]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[16]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[17]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[18]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[19]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[20]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[21]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[22]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[23]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[24]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[25]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[26]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[27]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[28]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[29]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[30]} {EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0/inst/bclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0/inst/lrclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list EQ_27_band_i/axi_i2s_receiver_0/inst/m_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list SDATA_I_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
