# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Zynq_Book/EQ_27_band/eq_27_zedboard.xdc

# XDC: new/clock_constraints.xdc

# Block Designs: bd/EQ_27_band/EQ_27_band.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band || ORIG_REF_NAME==EQ_27_band} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_axi_i2s_receiver_0_0/EQ_27_band_axi_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_axi_i2s_receiver_0_0 || ORIG_REF_NAME==EQ_27_band_axi_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_eq_core_0_0/EQ_27_band_eq_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_eq_core_0_0 || ORIG_REF_NAME==EQ_27_band_eq_core_0_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_axi_i2s_transmitter_0_0/EQ_27_band_axi_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_axi_i2s_transmitter_0_0 || ORIG_REF_NAME==EQ_27_band_axi_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_processing_system7_0_0/EQ_27_band_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_processing_system7_0_0 || ORIG_REF_NAME==EQ_27_band_processing_system7_0_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_axi_interconnect_0_0/EQ_27_band_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_axi_interconnect_0_0 || ORIG_REF_NAME==EQ_27_band_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_axi_gpio_0_0 || ORIG_REF_NAME==EQ_27_band_axi_gpio_0_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_rst_ps7_0_100M_0/EQ_27_band_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_rst_ps7_0_100M_0 || ORIG_REF_NAME==EQ_27_band_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_xbar_0/EQ_27_band_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_xbar_0 || ORIG_REF_NAME==EQ_27_band_xbar_0} -quiet] -quiet

# IP: bd/EQ_27_band/ip/EQ_27_band_auto_pc_0/EQ_27_band_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_27_band_auto_pc_0 || ORIG_REF_NAME==EQ_27_band_auto_pc_0} -quiet] -quiet

# XDC: bd/EQ_27_band/EQ_27_band_ooc.xdc
