# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Zynq_Book/EQ_27_band/EQ_27_band.cache/wt [current_project]
set_property parent.project_path C:/Zynq_Book/EQ_27_band/EQ_27_band.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Zynq_Book/ip_repo/axi_i2s_receiver_1.0
  c:/Zynq_Book/ip_repo/axi_i2s_transmitter
  c:/Zynq_Book/ip_repo/eq_core
} [current_project]
set_property ip_output_repo c:/Zynq_Book/EQ_27_band/EQ_27_band.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/hdl/EQ_27_band_wrapper.v
add_files C:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/EQ_27_band.bd
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_processing_system7_0_0/EQ_27_band_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_axi_gpio_0_0/EQ_27_band_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_rst_ps7_0_100M_0/EQ_27_band_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_rst_ps7_0_100M_0/EQ_27_band_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_rst_ps7_0_100M_0/EQ_27_band_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_xbar_0/EQ_27_band_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/ip/EQ_27_band_auto_pc_0/EQ_27_band_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/sources_1/bd/EQ_27_band/EQ_27_band_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Zynq_Book/EQ_27_band/eq_27_zedboard.xdc
set_property used_in_implementation false [get_files C:/Zynq_Book/EQ_27_band/eq_27_zedboard.xdc]

read_xdc C:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/constrs_1/new/clock_constraints.xdc
set_property used_in_implementation false [get_files C:/Zynq_Book/EQ_27_band/EQ_27_band.srcs/constrs_1/new/clock_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top EQ_27_band_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EQ_27_band_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EQ_27_band_wrapper_utilization_synth.rpt -pb EQ_27_band_wrapper_utilization_synth.pb"
